/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QPushButton *pushButton_2;
    QPushButton *pushButton_1;
    QPushButton *push1;
    QPushButton *push2;
    QPushButton *push3;
    QPushButton *push4;
    QPushButton *push5;
    QPushButton *push6;
    QPushButton *push7;
    QPushButton *push8;
    QPushButton *push9;
    QPushButton *push0;
    QPushButton *pushEqually;
    QPushButton *pushdot;
    QPushButton *pushPlus;
    QPushButton *pushMinus;
    QPushButton *pushMultiply;
    QPushButton *pushDivide;
    QPushButton *pushDelete;
    QPushButton *pushRoot;
    QLabel *mainDert;
    QTableWidget *mainDertTabl;
    QPushButton *addTabl;
    QTableWidget *interestChargesTab;
    QLabel *interestCharges;
    QLabel *labelDay;
    QLabel *labelPercent;
    QDoubleSpinBox *percent;
    QSpinBox *days;
    QPushButton *totals;
    QPushButton *test1;
    QPushButton *test2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(780, 650);
        MainWindow->setStyleSheet(QStringLiteral(""));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setEnabled(true);
        centralWidget->setMouseTracking(false);
        centralWidget->setAcceptDrops(false);
        centralWidget->setLayoutDirection(Qt::LeftToRight);
        centralWidget->setStyleSheet(QLatin1String("QWidget#centralWidget {\n"
"background-image:url(:/image/7SPBY-hxP6A.jpg);\n"
"};"));
        centralWidget->setInputMethodHints(Qt::ImhNone);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(220, 90, 340, 60));
        QFont font;
        font.setFamily(QStringLiteral("Times New Roman"));
        font.setPointSize(15);
        label->setFont(font);
        label->setStyleSheet(QLatin1String("background-color:rgb(255, 255, 135);\n"
"border-color:rgb(0, 0, 0);\n"
"border-radius: 30px;\n"
"color:rgb(0, 0, 0);\n"
"font-size: 15pt;\n"
"qproperty-alignment: AlignCenter;\n"
"padding: 0 20px 0 20px;"));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(390, 0, 390, 80));
        QPalette palette;
        QBrush brush(QColor(254, 254, 190, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(255, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        QBrush brush2(QColor(120, 120, 120, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushButton_2->setPalette(palette);
        QFont font1;
        font1.setFamily(QStringLiteral("Times New Roman"));
        font1.setPointSize(22);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        pushButton_2->setFont(font1);
        pushButton_2->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_2->setAutoFillBackground(false);
        pushButton_2->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushButton_1 = new QPushButton(centralWidget);
        pushButton_1->setObjectName(QStringLiteral("pushButton_1"));
        pushButton_1->setGeometry(QRect(0, 0, 390, 80));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushButton_1->setPalette(palette1);
        pushButton_1->setFont(font1);
        pushButton_1->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_1->setAutoFillBackground(false);
        pushButton_1->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push1 = new QPushButton(centralWidget);
        push1->setObjectName(QStringLiteral("push1"));
        push1->setGeometry(QRect(240, 400, 50, 50));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push1->setPalette(palette2);
        push1->setFont(font1);
        push1->setCursor(QCursor(Qt::PointingHandCursor));
        push1->setAutoFillBackground(false);
        push1->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push2 = new QPushButton(centralWidget);
        push2->setObjectName(QStringLiteral("push2"));
        push2->setGeometry(QRect(320, 400, 50, 50));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push2->setPalette(palette3);
        push2->setFont(font1);
        push2->setCursor(QCursor(Qt::PointingHandCursor));
        push2->setAutoFillBackground(false);
        push2->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push3 = new QPushButton(centralWidget);
        push3->setObjectName(QStringLiteral("push3"));
        push3->setGeometry(QRect(400, 400, 50, 50));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push3->setPalette(palette4);
        push3->setFont(font1);
        push3->setCursor(QCursor(Qt::PointingHandCursor));
        push3->setAutoFillBackground(false);
        push3->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push4 = new QPushButton(centralWidget);
        push4->setObjectName(QStringLiteral("push4"));
        push4->setGeometry(QRect(240, 320, 50, 50));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push4->setPalette(palette5);
        push4->setFont(font1);
        push4->setCursor(QCursor(Qt::PointingHandCursor));
        push4->setAutoFillBackground(false);
        push4->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push5 = new QPushButton(centralWidget);
        push5->setObjectName(QStringLiteral("push5"));
        push5->setGeometry(QRect(320, 320, 50, 50));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push5->setPalette(palette6);
        push5->setFont(font1);
        push5->setCursor(QCursor(Qt::PointingHandCursor));
        push5->setAutoFillBackground(false);
        push5->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push6 = new QPushButton(centralWidget);
        push6->setObjectName(QStringLiteral("push6"));
        push6->setGeometry(QRect(400, 320, 50, 50));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push6->setPalette(palette7);
        push6->setFont(font1);
        push6->setCursor(QCursor(Qt::PointingHandCursor));
        push6->setAutoFillBackground(false);
        push6->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push7 = new QPushButton(centralWidget);
        push7->setObjectName(QStringLiteral("push7"));
        push7->setGeometry(QRect(240, 240, 50, 50));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push7->setPalette(palette8);
        push7->setFont(font1);
        push7->setCursor(QCursor(Qt::PointingHandCursor));
        push7->setAutoFillBackground(false);
        push7->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push8 = new QPushButton(centralWidget);
        push8->setObjectName(QStringLiteral("push8"));
        push8->setGeometry(QRect(320, 240, 50, 50));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push8->setPalette(palette9);
        push8->setFont(font1);
        push8->setCursor(QCursor(Qt::PointingHandCursor));
        push8->setAutoFillBackground(false);
        push8->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push9 = new QPushButton(centralWidget);
        push9->setObjectName(QStringLiteral("push9"));
        push9->setGeometry(QRect(400, 240, 50, 50));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push9->setPalette(palette10);
        push9->setFont(font1);
        push9->setCursor(QCursor(Qt::PointingHandCursor));
        push9->setAutoFillBackground(false);
        push9->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        push0 = new QPushButton(centralWidget);
        push0->setObjectName(QStringLiteral("push0"));
        push0->setGeometry(QRect(240, 480, 50, 50));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush);
        push0->setPalette(palette11);
        push0->setFont(font1);
        push0->setCursor(QCursor(Qt::PointingHandCursor));
        push0->setAutoFillBackground(false);
        push0->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushEqually = new QPushButton(centralWidget);
        pushEqually->setObjectName(QStringLiteral("pushEqually"));
        pushEqually->setGeometry(QRect(400, 480, 130, 50));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushEqually->setPalette(palette12);
        pushEqually->setFont(font1);
        pushEqually->setCursor(QCursor(Qt::PointingHandCursor));
        pushEqually->setAutoFillBackground(false);
        pushEqually->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushdot = new QPushButton(centralWidget);
        pushdot->setObjectName(QStringLiteral("pushdot"));
        pushdot->setGeometry(QRect(320, 480, 50, 50));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushdot->setPalette(palette13);
        pushdot->setFont(font1);
        pushdot->setCursor(QCursor(Qt::PointingHandCursor));
        pushdot->setAutoFillBackground(false);
        pushdot->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushPlus = new QPushButton(centralWidget);
        pushPlus->setObjectName(QStringLiteral("pushPlus"));
        pushPlus->setGeometry(QRect(480, 320, 50, 130));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushPlus->setPalette(palette14);
        pushPlus->setFont(font1);
        pushPlus->setCursor(QCursor(Qt::PointingHandCursor));
        pushPlus->setAutoFillBackground(false);
        pushPlus->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushMinus = new QPushButton(centralWidget);
        pushMinus->setObjectName(QStringLiteral("pushMinus"));
        pushMinus->setGeometry(QRect(480, 240, 50, 50));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushMinus->setPalette(palette15);
        pushMinus->setFont(font1);
        pushMinus->setCursor(QCursor(Qt::PointingHandCursor));
        pushMinus->setAutoFillBackground(false);
        pushMinus->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushMultiply = new QPushButton(centralWidget);
        pushMultiply->setObjectName(QStringLiteral("pushMultiply"));
        pushMultiply->setGeometry(QRect(240, 160, 50, 50));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushMultiply->setPalette(palette16);
        pushMultiply->setFont(font1);
        pushMultiply->setCursor(QCursor(Qt::PointingHandCursor));
        pushMultiply->setAutoFillBackground(false);
        pushMultiply->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushDivide = new QPushButton(centralWidget);
        pushDivide->setObjectName(QStringLiteral("pushDivide"));
        pushDivide->setGeometry(QRect(320, 160, 50, 50));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushDivide->setPalette(palette17);
        pushDivide->setFont(font1);
        pushDivide->setCursor(QCursor(Qt::PointingHandCursor));
        pushDivide->setAutoFillBackground(false);
        pushDivide->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushDelete = new QPushButton(centralWidget);
        pushDelete->setObjectName(QStringLiteral("pushDelete"));
        pushDelete->setGeometry(QRect(480, 160, 50, 50));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushDelete->setPalette(palette18);
        pushDelete->setFont(font1);
        pushDelete->setCursor(QCursor(Qt::PointingHandCursor));
        pushDelete->setAutoFillBackground(false);
        pushDelete->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        pushRoot = new QPushButton(centralWidget);
        pushRoot->setObjectName(QStringLiteral("pushRoot"));
        pushRoot->setGeometry(QRect(400, 160, 50, 50));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pushRoot->setPalette(palette19);
        pushRoot->setFont(font1);
        pushRoot->setCursor(QCursor(Qt::PointingHandCursor));
        pushRoot->setAutoFillBackground(false);
        pushRoot->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        mainDert = new QLabel(centralWidget);
        mainDert->setObjectName(QStringLiteral("mainDert"));
        mainDert->setGeometry(QRect(50, 90, 301, 61));
        mainDert->setFont(font);
        mainDert->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        mainDertTabl = new QTableWidget(centralWidget);
        if (mainDertTabl->columnCount() < 3)
            mainDertTabl->setColumnCount(3);
        QFont font2;
        font2.setFamily(QStringLiteral("Avdira"));
        font2.setPointSize(10);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setFont(font2);
        mainDertTabl->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        mainDertTabl->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        mainDertTabl->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        mainDertTabl->setObjectName(QStringLiteral("mainDertTabl"));
        mainDertTabl->setEnabled(true);
        mainDertTabl->setGeometry(QRect(60, 160, 480, 200));
        mainDertTabl->setStyleSheet(QLatin1String("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);"));
        mainDertTabl->verticalHeader()->setVisible(false);
        mainDertTabl->verticalHeader()->setCascadingSectionResizes(false);
        mainDertTabl->verticalHeader()->setHighlightSections(true);
        mainDertTabl->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        mainDertTabl->verticalHeader()->setStretchLastSection(false);
        addTabl = new QPushButton(centralWidget);
        addTabl->setObjectName(QStringLiteral("addTabl"));
        addTabl->setGeometry(QRect(470, 220, 51, 51));
        addTabl->setCursor(QCursor(Qt::PointingHandCursor));
        addTabl->setStyleSheet(QLatin1String("border-image: url(:/image/add.png);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);"));
        interestChargesTab = new QTableWidget(centralWidget);
        if (interestChargesTab->columnCount() < 2)
            interestChargesTab->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setFont(font2);
        interestChargesTab->setHorizontalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        interestChargesTab->setHorizontalHeaderItem(1, __qtablewidgetitem4);
        interestChargesTab->setObjectName(QStringLiteral("interestChargesTab"));
        interestChargesTab->setEnabled(true);
        interestChargesTab->setGeometry(QRect(50, 410, 480, 200));
        QPalette palette20;
        QBrush brush3(QColor(255, 255, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette20.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        interestChargesTab->setPalette(palette20);
        interestChargesTab->setStyleSheet(QLatin1String("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);"));
        interestChargesTab->setShowGrid(true);
        interestChargesTab->setSortingEnabled(false);
        interestChargesTab->setWordWrap(true);
        interestChargesTab->setCornerButtonEnabled(true);
        interestChargesTab->verticalHeader()->setVisible(false);
        interestChargesTab->verticalHeader()->setHighlightSections(true);
        interestCharges = new QLabel(centralWidget);
        interestCharges->setObjectName(QStringLiteral("interestCharges"));
        interestCharges->setGeometry(QRect(50, 370, 301, 41));
        interestCharges->setFont(font);
        interestCharges->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        labelDay = new QLabel(centralWidget);
        labelDay->setObjectName(QStringLiteral("labelDay"));
        labelDay->setGeometry(QRect(560, 170, 200, 20));
        QFont font3;
        font3.setFamily(QStringLiteral("Times New Roman"));
        font3.setPointSize(12);
        labelDay->setFont(font3);
        labelDay->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        labelPercent = new QLabel(centralWidget);
        labelPercent->setObjectName(QStringLiteral("labelPercent"));
        labelPercent->setGeometry(QRect(560, 240, 210, 20));
        QFont font4;
        font4.setFamily(QStringLiteral("Times New Roman"));
        font4.setPointSize(12);
        font4.setBold(false);
        font4.setWeight(50);
        labelPercent->setFont(font4);
        labelPercent->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        percent = new QDoubleSpinBox(centralWidget);
        percent->setObjectName(QStringLiteral("percent"));
        percent->setGeometry(QRect(560, 270, 200, 30));
        percent->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);"));
        percent->setDecimals(3);
        percent->setMaximum(1e+11);
        percent->setSingleStep(0.5);
        days = new QSpinBox(centralWidget);
        days->setObjectName(QStringLiteral("days"));
        days->setGeometry(QRect(560, 200, 200, 30));
        days->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);"));
        days->setMaximum(31);
        totals = new QPushButton(centralWidget);
        totals->setObjectName(QStringLiteral("totals"));
        totals->setGeometry(QRect(560, 320, 201, 31));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush);
        totals->setPalette(palette21);
        QFont font5;
        font5.setFamily(QStringLiteral("Times New Roman"));
        font5.setPointSize(12);
        font5.setBold(false);
        font5.setItalic(false);
        font5.setWeight(50);
        totals->setFont(font5);
        totals->setCursor(QCursor(Qt::PointingHandCursor));
        totals->setAutoFillBackground(false);
        totals->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        test1 = new QPushButton(centralWidget);
        test1->setObjectName(QStringLiteral("test1"));
        test1->setGeometry(QRect(560, 370, 91, 51));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush);
        test1->setPalette(palette22);
        test1->setFont(font5);
        test1->setCursor(QCursor(Qt::PointingHandCursor));
        test1->setAutoFillBackground(false);
        test1->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        test2 = new QPushButton(centralWidget);
        test2->setObjectName(QStringLiteral("test2"));
        test2->setGeometry(QRect(670, 370, 91, 51));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush);
        test2->setPalette(palette23);
        test2->setFont(font5);
        test2->setCursor(QCursor(Qt::PointingHandCursor));
        test2->setAutoFillBackground(false);
        test2->setStyleSheet(QStringLiteral("background-color: rgb(254, 254, 190);"));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 780, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "\n"
"0", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "\320\232\321\200\320\265\320\264\320\270\321\202\320\275\321\213\320\271 \320\232\320\260\320\273\321\214\320\272\321\203\320\273\321\217\321\202\320\276\321\200", Q_NULLPTR));
        pushButton_1->setText(QApplication::translate("MainWindow", "\320\220\321\200\320\265\321\204\320\274\320\265\321\202\320\270\321\207\320\265\321\201\320\272\320\270\320\271 \320\232\320\260\320\273\321\214\320\272\321\203\320\273\321\217\321\202\320\276\321\200", Q_NULLPTR));
        push1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        push2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        push3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        push4->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        push5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        push6->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        push7->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        push8->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        push9->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        push0->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        pushEqually->setText(QApplication::translate("MainWindow", "=", Q_NULLPTR));
        pushdot->setText(QApplication::translate("MainWindow", ".", Q_NULLPTR));
        pushPlus->setText(QApplication::translate("MainWindow", "+", Q_NULLPTR));
        pushMinus->setText(QApplication::translate("MainWindow", "-", Q_NULLPTR));
        pushMultiply->setText(QApplication::translate("MainWindow", "*", Q_NULLPTR));
        pushDivide->setText(QApplication::translate("MainWindow", "/", Q_NULLPTR));
        pushDelete->setText(QApplication::translate("MainWindow", "\342\206\220", Q_NULLPTR));
        pushRoot->setText(QApplication::translate("MainWindow", "\342\210\232", Q_NULLPTR));
        mainDert->setText(QApplication::translate("MainWindow", "\320\242\320\260\320\261\320\273\320\270\321\206\320\260 \320\276\321\201\320\275\320\276\320\262\320\275\320\276\320\263\320\276 \320\264\320\276\320\273\320\263\320\260", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem = mainDertTabl->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "\320\224\320\260\321\202\320\260", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem1 = mainDertTabl->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "\320\237\320\276\321\201\321\202\321\203\320\277\320\273\320\265\320\275\320\270\320\265 \320\264\320\276\320\273\320\263\320\260", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem2 = mainDertTabl->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "\320\237\320\276\320\263\320\260\321\210\320\265\320\275\320\270\320\265 \320\264\320\276\320\273\320\263\320\260", Q_NULLPTR));
        addTabl->setText(QString());
        QTableWidgetItem *___qtablewidgetitem3 = interestChargesTab->horizontalHeaderItem(0);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "\320\224\320\260\321\202\320\260 \320\275\320\260\321\207\320\270\321\201\320\273\320\265\320\275\320\270\321\217", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem4 = interestChargesTab->horizontalHeaderItem(1);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "\320\235\320\260\321\207\320\270\321\201\320\273\320\265\320\275\320\276 \320\267\320\260 \320\274\320\265\321\201\321\217\321\206", Q_NULLPTR));
        interestCharges->setText(QApplication::translate("MainWindow", "\320\242\320\260\320\261\320\273\320\270\321\206\320\260 \320\275\320\260\321\207\320\270\321\201\320\273\320\265\320\275\320\275\321\213\321\205 \320\277\321\200\320\276\321\206\320\265\320\275\321\202\320\276\320\262", Q_NULLPTR));
        labelDay->setText(QApplication::translate("MainWindow", "\320\224\320\260\321\202\320\260 \320\275\320\260\321\207\320\270\321\201\320\273\320\265\320\275\320\270\321\217 \320\277\321\200\320\276\321\206\320\265\320\275\321\202\320\276\320\262", Q_NULLPTR));
        labelPercent->setText(QApplication::translate("MainWindow", "\320\237\321\200\320\276\321\206\320\265\320\275\321\202\320\275\320\260\321\217 \321\201\321\202\320\260\320\262\320\272\320\260 (\320\263\320\276\320\264\320\276\320\262\321\213\321\205)", Q_NULLPTR));
        totals->setText(QApplication::translate("MainWindow", "\320\240\320\260\321\201\321\201\321\207\320\270\321\202\320\260\321\202\321\214", Q_NULLPTR));
        test1->setText(QApplication::translate("MainWindow", "\321\202\320\265\321\201\321\202", Q_NULLPTR));
        test2->setText(QApplication::translate("MainWindow", "\321\202\320\265\321\201\321\202", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
